### ISSUE TITLE
invalid conversion from private to public 

### ISSUE THREAD

**Issue by akhoroshev** [namuyan/nem-ed25519#1]
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nem_ed25519.key import secret_key, public_key, get_address
>>> sk = '00e41ce1fde60bbad7c9458d42d1a7f81a8cb2899adabef851781d21e9507372f7'
>>> print(public_key(sk))
ff7ef524fe822f54079e43c1debf749bbe43739e7ed1b2f41888c512d53d9972

but this site https://output.jsbin.com/zifipel correctly convert the key:
private: 00e41ce1fde60bbad7c9458d42d1a7f81a8cb2899adabef851781d21e9507372f7
public: 2d0cf680fa6598934152857da2b5863eacb7451f2689e18b2cd33dbd19ed9181

**Comment by namuyan** [comment]
Thank you for bug report.
Are you create a keypairs by `http://127.0.0.1:7890/account/generate` ?
The API often contains double zero prefix. Your sk is 66 letters. Prefix `00` is nonsense.
I will add assert raise for developers.

**Comment by akhoroshev** [comment]
Thank for your reply.
Yes, I generated the keys using http://127.0.0.1:7890/account/generate
