### ISSUE TITLE
Is the signing method secure?

### ISSUE THREAD

**Issue by yzhang1994** [namuyan/nem-ed25519#5]
I found this in the `nem-py` repo:

https://github.com/NemProject/nem-py/blob/master/ed25519.py

I noticed the code for signature generation is almost identical. But there's no warning about the potential security issue (in the docstring of the file linked above). Have you addressed the issue?

**Comment by namuyan** [comment]
Thank you for comment!
I add the doc but I've stopped maintenance and archived it.
